name: Terraform 
on:
    push:
        branches:
            - task1
    pull_request:
        branches:
            - main

permissions:
    id-token: write
    contents: read

jobs:
    terraform-check:
        name: "Terraform Check"
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Terraform Install
              uses: hashicorp/setup-terraform@v3

            - name: "Configure Credentials"
              uses: aws-actions/configure-aws-credentials@v4
              with:
                  audience: sts.amazonaws.com
                  aws-region: eu-central-1
                  role-to-assume: arn:aws:iam::539247481877:role/GithubActionsRole


            - name: Terraform Init
              run: terraform init -input=false

            - name: Terraform Format
              run: terraform fmt -check

    terraform-plan:
        name: "Terraform Plan"
        runs-on: ubuntu-latest
        needs: [terraform-check]
        outputs:
          tfPlanExitCode: ${{ steps.tf-plan.outputs.exitcode }}
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Terraform Install
              uses: hashicorp/setup-terraform@v3

            - name: "Configure Credentials"
              uses: aws-actions/configure-aws-credentials@v4
              with:
                  audience: sts.amazonaws.com
                  aws-region: eu-central-1
                  role-to-assume: arn:aws:iam::539247481877:role/GithubActionsRole


            - name: Terraform Init
              run: terraform init -input=false

            - name: Perform Terraform Plan
              id: tf-plan
              run: |
                export exitcode=0
                terraform plan -detailed-exitcode -no-color -out tfplan || export exitcode=$?
                echo "exitcode=$exitcode" >> $GITHUB_OUTPUT
                if [ $exitcode -eq 1 ]; then
                echo Terraform Plan Failed!
                    exit 1
                  else
                    exit 0
                fi
            - name: Publish Terraform Plan
              uses: actions/upload-artifact@v4
              with:
                  name: tfplan
                  path: tfplan

    terraform-apply:
        name: "Terraform Apply"
        runs-on: ubuntu-latest
        needs: [terraform-check, terraform-plan]
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Terraform Install
              uses: hashicorp/setup-terraform@v3

            - name: "Configure Credentials"
              uses: aws-actions/configure-aws-credentials@v4
              with:
                  audience: sts.amazonaws.com
                  aws-region: eu-central-1
                  role-to-assume: aarn:aws:iam::539247481877:role/GithubActionsRole


            - name: Terraform Init
              run: terraform init

            - name: Download Terraform Plan
              uses: actions/download-artifact@v4
              with:
                name: tfplan
            - run: terraform apply -auto-approve tfplan